#!/usr/bin/env bash
# llm-usage.tmux — TPM entry point for tmux-llm-usage.
#
# On load it (1) reads the @llm-usage-* options, (2) resolves an absolute jq
# path while it still has a normal PATH, (3) writes a small sourced config file
# into the cache dir so the hot-path reader (scripts/usage.sh) never has to call
# tmux itself, and (4) replaces the literal token `#{llm_usage}` wherever it
# appears in status-left / status-right with a `#(scripts/usage.sh)` call.
#
# The reader is fully non-blocking: `#()` only ever reads a pre-rendered cache.
# NEVER use `set -e` here — an unset option or absent status line is expected.

set -u

CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USAGE_SCRIPT="$CURRENT_DIR/scripts/usage.sh"
TOKEN='#{llm_usage}'

get_tmux_option() {
  local option="$1" default="$2" value
  value="$(tmux show-option -gqv "$option" 2>/dev/null)"
  if [ -n "$value" ]; then
    printf '%s' "$value"
  else
    printf '%s' "$default"
  fi
}

# Cache dir — MUST match scripts/usage.sh cache_dir().
cache_dir() {
  printf '%s/tmux-llm-usage-%s' "${TMUX_TMPDIR:-/tmp}" "$(id -u)"
}

# 0700 dir, refuse a pre-planted symlink (defence against /tmp races).
ensure_cache_dir() {
  local d="$1"
  [ -L "$d" ] && return 1
  [ -d "$d" ] || ( umask 077; mkdir -p "$d" ) 2>/dev/null || return 1
  [ -d "$d" ] && [ ! -L "$d" ]
}

# Single-quote a value for safe inclusion in the sourced config file. Any
# embedded single quote becomes the classic '\'' sequence, so the provider
# string is stored as inert data — it is only ever executed later, on purpose,
# by usage.sh via `sh -c`.
sq() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

main() {
  local cdir config provider interval fmt maxseg timeout jqbin

  cdir="$(cache_dir)"
  ensure_cache_dir "$cdir" || return 0
  config="$cdir/config.sh"

  provider="$(get_tmux_option "@llm-usage-provider" "")"
  interval="$(get_tmux_option "@llm-usage-interval" "60")"
  fmt="$(get_tmux_option "@llm-usage-format" "label value")"
  maxseg="$(get_tmux_option "@llm-usage-max-segments" "4")"
  timeout="$(get_tmux_option "@llm-usage-timeout" "10")"
  jqbin="$(command -v jq 2>/dev/null || true)"

  # Write the config atomically. Values are single-quoted data assignments.
  {
    printf '# generated by llm-usage.tmux — do not edit; change @llm-usage-* in tmux.conf\n'
    printf 'LLM_PROVIDER=%s\n' "$(sq "$provider")"
    printf 'LLM_INTERVAL=%s\n' "$(sq "$interval")"
    printf 'LLM_FORMAT=%s\n'   "$(sq "$fmt")"
    printf 'LLM_MAX=%s\n'      "$(sq "$maxseg")"
    printf 'LLM_TIMEOUT=%s\n'  "$(sq "$timeout")"
    printf 'LLM_JQ=%s\n'       "$(sq "$jqbin")"
  } >"$config.tmp" 2>/dev/null && mv "$config.tmp" "$config" 2>/dev/null

  # First-load guidance when the required provider is not set: point the user at
  # the README / examples instead of silently showing nothing.
  if [ -z "$provider" ]; then
    tmux display-message \
      "tmux-llm-usage: set @llm-usage-provider to a command that prints usage JSON — see README (try examples/static.sh for a 30-second demo)" \
      2>/dev/null
  fi

  if [ -z "$jqbin" ]; then
    tmux display-message \
      "tmux-llm-usage: jq not found on PATH — install it (e.g. 'brew install jq') so provider JSON can be parsed" \
      2>/dev/null
  fi

  # Interpolate the token into the status line(s). Only rewrite an option that
  # actually contains the token, so we never disturb an unrelated status layout.
  local repl option value
  repl="#($USAGE_SCRIPT)"
  for option in status-left status-right; do
    value="$(tmux show-option -gqv "$option" 2>/dev/null)"
    case "$value" in
      *"$TOKEN"*)
        tmux set-option -gq "$option" "${value//"$TOKEN"/$repl}"
        ;;
    esac
  done
}

main
